### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by kingchenc** [ZabuzaW/BattleCalculator-Freewar#1]
Hey,

danke erstmal, und ich weiss nicht ob du hier noch aktiv dran bist ^^ aber ein versuch ist es ja wert ^^

Nette sache, aber funktioniert teilweise nicht :/

1. Wenn mehrere NPCs auf einem Feld sind, und man besiegt 1, dann verschwinden die Werte von allen anderen.

2. Zeigt mir Blau (unique) und wins an, selbst wenn ich 0 Leben hab, zeigt es nicht rot an, sondern - lebenspunkte und den schnellangriff^^

3. nach ner stunde in chrome + tampermonkey hatt ich oben beim symbol über 1000 stehen in roter farbe :D normal? Sollte da nich 2 stehen für 2 aktive scripts? Die zahl erhöht sich jedesmal, wenn man ein feld geht oder aktualisiere

Im code selbst:

Nach "// ==/UserScript=="

das hinzufügen

/* globals jQuery, $, waitForKeyElements */

dann gibt es kein Error: eslint: no-undef - $ is not defined"

**Comment by Zabuzard** [comment]
Hi 😃 Sorry, aber wie du vermutet hast, bin ich nicht mehr wirklich dabei.

Falls du die Probleme behoben bekommst, kannst du gerne eine PR aufmachen und dann merge ich das gerne rein 👍

**Comment by kingchenc** [comment]
Kein Problem, dacht ich mir fast schon, hab freewar nach 10 Jahren wieder für mich entdeckt ^^ :D 

2. ist fixxed > PR
3. ist kein bug vom script, sondern die settings von tampermonkey... Icon-Information > active usercripts...

zum 1. hab ich noch keine idee warum nach einem angriff alle anderen werte von den npcs weg sind (also die des scriptes)... hmm, vlt. hast du da eine idee?

**Comment by kingchenc** [comment]
Neuer PR:

Behoben: Bei einem Win die Farbe dark green + extra Infos hinter schnellangriff: LS = Lifeloss + NL = NewLife

Behoben: dass das script keine infos mehr anzeigt, wenn man ein npc angreift und andere npcs sind noch auf dem feld, sollte jetzt auch behoben sein mit einem MutationObserver in beiden scripten.

zusatz: defeat anzeige überarbeitet
zusatz: Angreifen entfernt wenn man defeated wird


edit: npc liste ist auch fresh

und: java is nicht so mein ding das ding ging nich mehr, kurz in 5 min was in c# gecoded, source code liegt im PR

so, alles fixxed :D

**Comment by kingchenc** [comment]
Supi :) 

Ich close mal hier ;)

die tage kommt noch was kleines von mir... und ein bot ist auch noch geplant :D xD
